# Generated by Django 6.0.3 on 2026-03-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('Attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('employee_id', 'date')},
            },
        ),
    ]
